import {
  Activity,
  AlertCircle,
  Award,
  Bell,
  Bookmark,
  BookOpen,
  Briefcase,
  Bus,
  CalendarClock,
  CalendarDays,
  CheckCircle2,
  Clock,
  Compass,
  ExternalLink,
  FileText,
  FolderTree,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  HeartHandshake,
  HelpCircle,
  Home,
  Info,
  Layers,
  Link2,
  Mail,
  MapPin,
  Megaphone,
  Phone,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Trophy,
  Users,
  type LucideProps,
} from "lucide-react";
import type { ElementType } from "react";

export const AVAILABLE_NAV_ICONS: { name: string; label: string; icon: ElementType }[] = [
  { name: "Home", label: "Inicio / Casa", icon: Home },
  { name: "Megaphone", label: "Megáfono / Avisos", icon: Megaphone },
  { name: "CalendarDays", label: "Calendario / Fechas", icon: CalendarDays },
  { name: "CalendarClock", label: "Calendario y Reloj", icon: CalendarClock },
  { name: "FolderTree", label: "Carpetas / Recursos", icon: FolderTree },
  { name: "GraduationCap", label: "Birrete / Programas", icon: GraduationCap },
  { name: "Trophy", label: "Trofeo / Deportes", icon: Trophy },
  { name: "Bus", label: "Autobús / DART", icon: Bus },
  { name: "Clock", label: "Reloj / Horarios", icon: Clock },
  { name: "HeartHandshake", label: "Manos / Voluntariado", icon: HeartHandshake },
  { name: "Activity", label: "Actividad / Estado BFL", icon: Activity },
  { name: "Briefcase", label: "Maletín / Empleos", icon: Briefcase },
  { name: "HelpCircle", label: "Ayuda / Preguntas", icon: HelpCircle },
  { name: "Compass", label: "Brújula / Tutorial", icon: Compass },
  { name: "Users", label: "Usuarios / Equipos", icon: Users },
  { name: "BookOpen", label: "Libro / Artículos", icon: BookOpen },
  { name: "Phone", label: "Teléfono / Contacto", icon: Phone },
  { name: "Smartphone", label: "Móvil / Apps", icon: Smartphone },
  { name: "Globe", label: "Mundo / Enlaces", icon: Globe },
  { name: "ShieldCheck", label: "Escudo / Accesibilidad", icon: ShieldCheck },
  { name: "FileText", label: "Documento / Guía", icon: FileText },
  { name: "Layers", label: "Capas / Módulos", icon: Layers },
  { name: "Sparkles", label: "Destellos / Destacado", icon: Sparkles },
  { name: "ExternalLink", label: "Enlace Externo", icon: ExternalLink },
  { name: "Bell", label: "Campana / Notificaciones", icon: Bell },
  { name: "MapPin", label: "Ubicación / Mapa", icon: MapPin },
  { name: "Bookmark", label: "Marcador", icon: Bookmark },
  { name: "Info", label: "Información", icon: Info },
  { name: "Search", label: "Búsqueda", icon: Search },
  { name: "Award", label: "Premio / Reconocimiento", icon: Award },
  { name: "Mail", label: "Correo", icon: Mail },
  { name: "Star", label: "Estrella", icon: Star },
  { name: "Heart", label: "Corazón", icon: Heart },
  { name: "Headphones", label: "Audífonos / Podcasts", icon: Headphones },
  { name: "Link2", label: "Enlace", icon: Link2 },
];

const ICON_MAP: Record<string, ElementType> = {
  Home,
  Megaphone,
  CalendarDays,
  CalendarClock,
  FolderTree,
  GraduationCap,
  Trophy,
  Bus,
  Clock,
  HeartHandshake,
  Activity,
  Briefcase,
  HelpCircle,
  Compass,
  Users,
  BookOpen,
  Phone,
  Smartphone,
  Globe,
  ShieldCheck,
  FileText,
  Layers,
  Sparkles,
  ExternalLink,
  Bell,
  MapPin,
  Bookmark,
  Info,
  Search,
  Award,
  AlertCircle,
  CheckCircle2,
  Settings,
  Mail,
  Star,
  Share2,
  Heart,
  Headphones,
  Link2,
};

export function NavigationIcon({
  name,
  className = "size-4",
  ...props
}: {
  name?: string | null;
  className?: string;
} & LucideProps) {
  const IconComponent = (name && ICON_MAP[name]) || Link2;
  return <IconComponent className={className} aria-hidden="true" {...props} />;
}
