/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PersonalizadosRouteImport } from './routes/personalizados'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as TarjetasRouteImport } from './routes/tarjetas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizadosRoute = PersonalizadosRouteImport.update({
  id: '/personalizados',
  path: '/personalizados',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const TarjetasRoute = TarjetasRouteImport.update({
  id: '/tarjetas',
  path: '/tarjetas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/cuenta': typeof CuentaRoute
  '/galeria': typeof GaleriaRoute
  '/panel': typeof PanelRoute
  '/personalizados': typeof PersonalizadosRoute
  '/productos': typeof ProductosRoute
  '/restablecer': typeof RestablecerRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/cuenta': typeof CuentaRoute
  '/galeria': typeof GaleriaRoute
  '/panel': typeof PanelRoute
  '/personalizados': typeof PersonalizadosRoute
  '/productos': typeof ProductosRoute
  '/restablecer': typeof RestablecerRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/cuenta': typeof CuentaRoute
  '/galeria': typeof GaleriaRoute
  '/panel': typeof PanelRoute
  '/personalizados': typeof PersonalizadosRoute
  '/productos': typeof ProductosRoute
  '/restablecer': typeof RestablecerRoute
  '/tarjetas': typeof TarjetasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/cuenta'
    | '/galeria'
    | '/panel'
    | '/personalizados'
    | '/productos'
    | '/restablecer'
    | '/tarjetas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/cuenta'
    | '/galeria'
    | '/panel'
    | '/personalizados'
    | '/productos'
    | '/restablecer'
    | '/tarjetas'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/cuenta'
    | '/galeria'
    | '/panel'
    | '/personalizados'
    | '/productos'
    | '/restablecer'
    | '/tarjetas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CuentaRoute: typeof CuentaRoute
  GaleriaRoute: typeof GaleriaRoute
  PanelRoute: typeof PanelRoute
  PersonalizadosRoute: typeof PersonalizadosRoute
  ProductosRoute: typeof ProductosRoute
  RestablecerRoute: typeof RestablecerRoute
  TarjetasRoute: typeof TarjetasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizados': {
      id: '/personalizados'
      path: '/personalizados'
      fullPath: '/personalizados'
      preLoaderRoute: typeof PersonalizadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarjetas': {
      id: '/tarjetas'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof TarjetasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CuentaRoute: CuentaRoute,
  GaleriaRoute: GaleriaRoute,
  PanelRoute: PanelRoute,
  PersonalizadosRoute: PersonalizadosRoute,
  ProductosRoute: ProductosRoute,
  RestablecerRoute: RestablecerRoute,
  TarjetasRoute: TarjetasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
