// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    const jsonHeaders = {
      "content-type": "application/json; charset=utf-8",
      "content-range": "0-0/0",
    };
    const accept = headers.get("Accept") || headers.get("accept") || "";
    const emptyBody = accept.includes("application/vnd.pgrst.object+json") ? "null" : "[]";

    if (
      !supabaseKey ||
      supabaseKey === "dummy-anon-key" ||
      supabaseKey === "sb_publishable_nrtndalmngfwqidregma"
    ) {
      return new Response(emptyBody, { status: 200, headers: jsonHeaders });
    }

    try {
      const response = await fetch(input, { ...init, headers });
      if (response.status === 401) {
        return new Response(emptyBody, { status: 200, headers: jsonHeaders });
      }
      return response;
    } catch {
      return new Response(emptyBody, { status: 200, headers: jsonHeaders });
    }
  };
}

export function isServiceRoleConfigured(): boolean {
  const serviceKey = process.env["SUPABASE_SERVICE_ROLE_KEY"];
  if (!serviceKey) return false;
  if (serviceKey.startsWith("dummy") || serviceKey.length < 20) return false;
  return true;
}

export function getSanitizedProjectId(): string {
  const url = process.env["SUPABASE_URL"] || process.env["VITE_SUPABASE_URL"] || "";
  try {
    const host = new URL(url).hostname;
    const projectPart = host.split(".")[0];
    if (projectPart && projectPart.length > 6) {
      return `${projectPart.slice(0, 5)}...${projectPart.slice(-3)}`;
    }
    return projectPart || "no_configurado";
  } catch {
    return "no_configurado";
  }
}

export function hasValidServerDatabaseConfig(): boolean {
  const url = process.env["SUPABASE_URL"] || process.env["VITE_SUPABASE_URL"];
  if (!url || url.includes("127.0.0.1:54321")) return false;
  return isServiceRoleConfigured();
}

function getEffectiveServerKey(): string {
  const serviceKey = process.env["SUPABASE_SERVICE_ROLE_KEY"];
  const pubKey =
    process.env["SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["SUPABASE_ANON_KEY"] ||
    process.env["VITE_SUPABASE_ANON_KEY"];

  if (
    serviceKey &&
    (serviceKey.startsWith("sb_secret_") ||
      serviceKey.startsWith("eyJ") ||
      (!serviceKey.startsWith("dummy") && serviceKey.length > 20))
  ) {
    return serviceKey;
  }

  if (pubKey) {
    return pubKey;
  }

  return "dummy-anon-key";
}

function createSupabaseAdminClient() {
  const SUPABASE_URL =
    process.env["SUPABASE_URL"] ||
    process.env["VITE_SUPABASE_URL"] ||
    "https://nrtndalmngfwqidregma.supabase.co";
  const SUPABASE_KEY = getEffectiveServerKey();

  const isConfigured = Boolean(
    (process.env["SUPABASE_URL"] || process.env["VITE_SUPABASE_URL"]) &&
    (process.env["SUPABASE_SERVICE_ROLE_KEY"] ||
      process.env["SUPABASE_PUBLISHABLE_KEY"] ||
      process.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
      process.env["SUPABASE_ANON_KEY"] ||
      process.env["VITE_SUPABASE_ANON_KEY"]),
  );

  if (!isConfigured) {
    const missing = [
      ...(!process.env["SUPABASE_URL"] && !process.env["VITE_SUPABASE_URL"]
        ? ["SUPABASE_URL"]
        : []),
      ...(!process.env["SUPABASE_SERVICE_ROLE_KEY"] &&
      !process.env["SUPABASE_PUBLISHABLE_KEY"] &&
      !process.env["VITE_SUPABASE_PUBLISHABLE_KEY"]
        ? ["SUPABASE_SERVICE_ROLE_KEY"]
        : []),
    ];
    console.warn(
      `[Supabase] Note: Missing Supabase environment variable(s): ${missing.join(", ")}. Official sync will operate in offline/preview mode.`,
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
