// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createMockSupabaseClient() {
  console.warn(
    "[Supabase] Missing Supabase environment variable(s) — falling back to in-memory mock client",
  );
  const tableStore = new Map<string, Map<string, any>>();

  const getTable = (tableName: string) => {
    let t = tableStore.get(tableName);
    if (!t) {
      t = new Map<string, any>();
      tableStore.set(tableName, t);
    }
    return t;
  };

  const channelSubscribers = new Set<() => void>();

  const createQueryBuilder = (tableName: string) => {
    let filterEq: { field: string; value: any } | null = null;
    let filterIn: { field: string; values: any[] } | null = null;

    const builder: any = {
      select(_fields?: string) {
        return builder;
      },
      eq(field: string, value: any) {
        filterEq = { field, value };
        return builder;
      },
      in(field: string, values: any[]) {
        filterIn = { field, values };
        return builder;
      },
      async maybeSingle() {
        const table = getTable(tableName);
        let found: any = null;
        if (filterEq) {
          if (filterEq.field === "id") {
            const raw = table.get(String(filterEq.value));
            if (raw !== undefined) found = { id: filterEq.value, data: raw };
          } else {
            for (const [id, data] of table.entries()) {
              if (data && data[filterEq.field] === filterEq.value) {
                found = { id, data };
                break;
              }
            }
          }
        }
        return { data: found, error: null };
      },
      async single() {
        return builder.maybeSingle();
      },
      async insert(rows: any) {
        const table = getTable(tableName);
        const list = Array.isArray(rows) ? rows : [rows];
        for (const row of list) {
          const id = row.id || `mock_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
          table.set(id, row.data !== undefined ? row.data : row);
        }
        channelSubscribers.forEach((cb) => {
          try {
            cb();
          } catch (_) {}
        });
        return { data: rows, error: null };
      },
      async upsert(rows: any) {
        const table = getTable(tableName);
        const list = Array.isArray(rows) ? rows : [rows];
        for (const row of list) {
          const id = row.id || `mock_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
          table.set(id, row.data !== undefined ? row.data : row);
        }
        channelSubscribers.forEach((cb) => {
          try {
            cb();
          } catch (_) {}
        });
        return { data: rows, error: null };
      },
      async delete() {
        const table = getTable(tableName);
        if (filterEq && filterEq.field === "id") {
          table.delete(String(filterEq.value));
        } else if (filterIn && filterIn.field === "id") {
          for (const val of filterIn.values) {
            table.delete(String(val));
          }
        }
        channelSubscribers.forEach((cb) => {
          try {
            cb();
          } catch (_) {}
        });
        return { data: null, error: null };
      },
      then(resolve: any, reject?: any) {
        const table = getTable(tableName);
        const result: any[] = [];
        for (const [id, data] of table.entries()) {
          result.push({ id, data });
        }
        return Promise.resolve({ data: result, error: null }).then(resolve, reject);
      },
    };
    return builder;
  };

  const mockAuth = {
    async getSession() {
      return { data: { session: null }, error: null };
    },
    onAuthStateChange(_callback: any) {
      return {
        data: {
          subscription: {
            unsubscribe: () => {},
          },
        },
      };
    },
    async signInWithPassword(_creds: any) {
      return {
        data: { user: null, session: null },
        error: new Error("Modo local activo: No hay credenciales de Supabase configuradas."),
      };
    },
    async signUp(_creds: any) {
      return {
        data: { user: null, session: null },
        error: new Error("Modo local activo: No hay credenciales de Supabase configuradas."),
      };
    },
    async signOut() {
      return { error: null };
    },
    async resetPasswordForEmail(_email: string) {
      return { error: null };
    },
    async updateUser(_attributes: any) {
      return { data: { user: null }, error: null };
    },
    async exchangeCodeForSession(_code: string) {
      return { data: { session: null }, error: null };
    },
    async setSession(_session: any) {
      return { data: { session: null }, error: null };
    },
    async getClaims(_token?: string) {
      return { data: null, error: null };
    },
  };

  return {
    auth: mockAuth,
    from: (tableName: string) => createQueryBuilder(tableName),
    channel: (_name: string) => {
      const channelObj: any = {
        on: (_event: string, _filter: any, callback: () => void) => {
          if (typeof callback === "function") {
            channelSubscribers.add(callback);
          }
          return channelObj;
        },
        subscribe: () => channelObj,
      };
      return channelObj;
    },
    removeChannel: (_channel: any) => {},
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering) and Node test runner
  const metaEnv =
    typeof import.meta !== "undefined" && import.meta.env ? import.meta.env : ({} as any);
  const nodeEnv = typeof process !== "undefined" && process.env ? process.env : ({} as any);

  const SUPABASE_URL = metaEnv["VITE_SUPABASE_URL"] || nodeEnv["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    metaEnv["VITE_SUPABASE_PUBLISHABLE_KEY"] || nodeEnv["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
